#!name=1blocker
#!desc=1blocker会员解锁
#!homepage=https://yfamily.ml
#!author=lutqhysky
#!icon=https://raw.githubusercontent.com/deezertidal/private/main/icons/1blocker.png

[Script]
1blocker= type=http-response,pattern=^https:\/\/api\.revenuecat\.com\/v1\/subscribers,requires-body=1,script-path=https://raw.githubusercontent.com/89996462/Quantumult-X/main/ycdz/blocker.js
[MITM]
hostname= %APPEND% api.revenuecat.com