#!name=阿布睡前故事
#!desc=阿布睡前故事解锁会员
#!homepage=https://yfamily.ml
#!author= 89996462
#!icon=https://raw.githubusercontent.com/deezertidal/private/main/icons/absqgs.png
[MITM]
hostname = %APPEND% tutugushiapi.tutuerge.com
[Script]
阿布睡前故事=type=http-response,pattern=http:\/\/tutugushiapi\.tutuerge\.com,requires-body=1,script-path=https://raw.githubusercontent.com/89996462/Quantumult-X/main/ycdz/abushuiqiangushi.js
