#!name=AccuWeather
#!desc=AccuWeather解锁会员
#!homepage=https://yfamily.ml
#!author=Marol62926
#!icon=https://raw.githubusercontent.com/deezertidal/private/main/icons/accu.png
[Script]
AccuWeather=type=http-response,pattern=https://app-subscription-proxy.accuweather.com/subscriptions/v1/apple/validate,script-path=https://raw.githubusercontent.com/Marol62926/MarScrpt/main/accuWeather.js,requires-body=1,max-size=0
[MITM]
hostname = %APPEND% app-subscription-proxy.accuweather.com
