#!name=AI换脸秀
#!desc=AI换脸秀会员解锁
#!homepage=https://yfamily.ml
#!author=89996462
#!icon=https://raw.githubusercontent.com/deezertidal/private/main/icons/ai.png
[Script]
AI换脸秀=type=http-response,pattern=^https:\/\/changeclothes\.szsszykj\.com\/interface\/GetIosVip.php,requires-body=1,script-path=https://raw.githubusercontent.com/89996462/Quantumult-X/main/ycdz/aihlx.js


[MITM]
hostname = %APPEND% changeclothes.szsszykj.com