#!name=APTV
#!desc=APTV解锁会员
#!homepage=https://github.com/deezertidal
#!author=89996462
#!icon=https://raw.githubusercontent.com/deezertidal/private/main/icons/aptv.png
[Script]
APTV=type=http-response,pattern=^https:\/\/buy\.itunes\.apple\.com\/verifyReceipt,requires-body=1,script-path=https://raw.githubusercontent.com/89996462/Quantumult-X/main/ycdz/aptv.js
[MITM]
hostname = %APPEND% buy.itunes.apple.com
