#!name=傲软PDF编辑
#!desc=傲软PDF编辑解锁会员
#!homepage=https://yfamily.ml
#!author=89996462
#!icon=https://raw.githubusercontent.com/deezertidal/private/main/icons/arpdfbj.png

[Script]
傲软PDF编辑=type=http-response,pattern=^https:\/\/gw\.aoscdn\.com\/base\/vip\/client\/authorizations,requires-body=1,script-path=https://raw.githubusercontent.com/89996462/Quantumult-X/main/ycdz/arpdf.js
[MITM] 
hostname = %APPEND% gw.aoscdn.com