#!name=傲软投屏
#!desc=傲软投屏解锁会员
#!homepage=https://yfamily.ml
#!author=89996462
#!icon=https://raw.githubusercontent.com/deezertidal/private/main/icons/artp.png

[Script]
傲软投屏=type=http-response,pattern=^https:\/\/awvp\.aoscdn\.com\/base\/vip\/client\/authorizations,requires-body=1,script-path=https://raw.githubusercontent.com/89996462/Quantumult-X/main/ycdz/artp.js
[MITM] 
hostname = %APPEND% awvp.aoscdn.com