#!name=波点音乐
#!desc=波点音乐去广告
#!homepage=https://yfamily.ml
#!author=zqzess
#!icon=https://raw.githubusercontent.com/deezertidal/private/main/icons/bodian2.png
[URL Rewrite]
^http:\/\/bd-api\.kuwo\.cn\/api\/service\/resource\/musicResource\/.+ _ reject
^https:\/\/bodiancdn\.kuwo\.cn\/.+\.mp4 _ reject
^http:\/\/bd-api\.kuwo\.cn\/api\/service\/resource\/view\?uid _ reject
^http:\/\/bd-api\.kuwo\.cn\/api\/service\/music\/recommendList\?uid _ reject
