#!name=充电助手
#!desc=充电助手解锁会员
#!homepage=https://yfamily.ml
#!author=89996462
#!icon=https://raw.githubusercontent.com/deezertidal/private/main/icons/cdzs.png

[Script]
充电助手=type=http-response,pattern=^https:\/\/api\.yonekura\.cn\/3\.7\.0\/uicommon\/getuser,requires-body=1,script-path=https://raw.githubusercontent.com/89996462/Quantumult-X/main/ycdz/cdzs.js
[MITM] 
hostname = %APPEND% api.yonekura.cn