#!name=Chic
#!desc=chic相机解锁会员
#!homepage=https://yfamily.ml
#!author=lutqhysky
#!icon=https://raw.githubusercontent.com/deezertidal/private/main/icons/chic.png

[Script]
Chic=type=http-response,pattern=^https:\/\/api-sub\.meitu\.com\/v2\/user\/vip_info\.json,requires-body=1,script-path=https://raw.githubusercontent.com/89996462/Quantumult-X/main/ycdz/Chic.js

[MITM] 
hostname= %APPEND% api-sub.meitu.com