#!name=彩云天气SVIP
#!desc=彩云天气会员解锁
#!homepage=https://github.com/deezertidal
#!author= ddgksf2013
#!icon=https://raw.githubusercontent.com/deezertidal/private/main/icons/caiyun.png
[MITM]
hostname = %APPEND% biz.caiyunapp.com
[Script]
彩云天气SVIP=type=http-response,pattern=https?:\/\/biz\.caiyunapp\.com\/(membership_rights|v2\/user),requires-body=1,script-path=https://raw.githubusercontent.com/deezertidal/private/master/js-backup/Crack/caiyun.js
