#!name=菜谱大全&香哈菜谱
#!desc=菜谱大全&香哈菜谱解锁会员
#!homepage=https://yfamily.ml
#!author= I-am-R-E
#!icon=https://raw.githubusercontent.com/deezertidal/private/main/icons/cp.png
[MITM]
hostname = %APPEND% apiios_dq.xiangha.com,apiios.xiangha.com
[Script]
菜谱大全&香哈菜谱1=type=http-response,pattern=^https?:\/\/apiios\.xiangha\.com\/main\d+\/,requires-body=1,script-path=https://raw.githubusercontent.com/I-am-R-E/QuantumultX/main/JavaScript/XiangHaCaiPu.js
菜谱大全&香哈菜谱2=type=http-response,pattern=^https?:\/\/apiios_dq\.xiangha\.com\/v\d\/,requires-body=1,script-path=https://raw.githubusercontent.com/I-am-R-E/QuantumultX/main/JavaScript/CaiPuDaQuan.js
菜谱大全&香哈菜谱3=type=http-response,pattern=^https?:\/\/appweb_dq\.xiangha\.com\/center\/pay\/home,requires-body=1,script-path=https://raw.githubusercontent.com/I-am-R-E/QuantumultX/main/JavaScript/CaiPuDaQuan.js