#!name=长相思
#!desc=长相思解锁会员
#!homepage=https://yfamily.ml
#!author= lutqhysky
#!icon=https://raw.githubusercontent.com/deezertidal/private/main/icons/cxs.png
[MITM]
hostname = %APPEND% poetry.yuan9.cn
[Script]
长相思=type=http-response,pattern=^https?:\/\/poetry\.yuan9\.cn\/api\/(order\/applesuccess|account\/login|User\/loginUserInfo),requires-body=1,script-path=https://raw.githubusercontent.com/lutqhysky/quantumultx/mylove/cxs/Script/cxs.js