#!name=大蓝鲸
#!desc=大蓝鲸解锁会员
#!homepage=https://yfamily.ml
#!author= lutqhysky
#!icon=https://raw.githubusercontent.com/deezertidal/private/main/icons/dalanjing.png



[MITM]
hostname = %APPEND% *.jstv.com

[Script]
大蓝鲸=type=http-response,pattern=^https?:\/\/(publish-dalanjing|publish-dalanjing|user-dalanjing)\.jstv\.com\/(search\/byArticleType|nav\/1554|PassportUser\/userinfo\/get),requires-body=1,script-path=https://raw.githubusercontent.com/lutqhysky/quantumultx/mylove/dalanjing/Script/dalanjing.js
