#!name=儿歌点点
#!desc=儿歌点点会员
#!homepage=https://yfamily.ml
#!author=ddgksf2013
#!icon=https://raw.githubusercontent.com/deezertidal/private/main/icons/egdd.png
[Script]
儿歌点点=type=http-response,pattern=http:\/\/gateway\.ergedd\.com\/dduser\/user\/center\/set,requires-body=1,script-path=https://github.com/deezertidal/private/raw/master/js-backup/Crack/egdd.js
[MITM]
hostname = %APPEND% gateway.ergedd.com