#!name=Fantastical
#!desc=Fantastical解锁会员
#!homepage=https://yfamily.ml
#!author=ddgksf2013
#!icon=https://raw.githubusercontent.com/deezertidal/private/main/icons/fantastical.png
[MITM]
hostname = %APPEND% api.flexibits.com
[Script]
Fantastical=type=http-response,pattern=^https:\/\/api\.flexibits\.com\/(v1\/auth\/device|v1\/account\/details),requires-body=1,script-path=https://raw.githubusercontent.com/deezertidal/private/master/js-backup/Crack/fantastical.js
