#!name=FoMz
#!desc=FoMz解锁会员
#!homepage=https://yfamily.ml
#!author=89996462
#!icon=https://raw.githubusercontent.com/deezertidal/private/main/icons/fomz.png



[Script]
FoMz=type=http-response,pattern=^https:\/\/fz68resapi\.imendon\.com\/v2\/purchase\/vip\/verification,requires-body=1,script-path=https://raw.githubusercontent.com/89996462/Quantumult-X/main/ycdz/FoMz.js



[MITM] 
hostname = %APPEND% fz68resapi.imendon.com
