#!name=海报工厂
#!desc=海报工厂解锁会员
#!homepage=https://yfamily.ml
#!author=89996462
#!icon=https://raw.githubusercontent.com/deezertidal/private/main/icons/hbgc.png


[Script]
海报工厂=type=http-response,pattern=^https:\/\/api-sub\.meitu\.com\/v2\/user\/vip_info_by_group\.json,requires-body=1,script-path=https://raw.githubusercontent.com/89996462/Quantumult-X/main/ycdz/hbgc.js


[MITM] 
hostname = %APPEND% api-sub.meitu.com
