#!name=烘焙小屋
#!desc=烘焙小屋解锁会员
#!homepage=https://yfamily.ml
#!author=yqc007
#!icon=https://raw.githubusercontent.com/deezertidal/private/main/icons/hbxw.png

[MITM]
hostname = %APPEND% apiios_dq.xiangha.com

[Script]
烘焙小屋=type=http-response,pattern=^https?:\/\/apiios_dq\.xiangha\.com\/v4\/(dish\/info|User\/getUserData)$,script-path=https://raw.githubusercontent.com/yqc007/QuantumultX/master/XiangHaBakeProCrack.js,requires-body=1
