#!name=好事发生
#!desc=好事发生解锁会员
#!homepage=https://yfamily.ml
#!author=89996462
#!icon=https://raw.githubusercontent.com/deezertidal/private/main/icons/hsfs.png

[Script]
好事发生=type=http-response,pattern=https://api.revenuecat.com/v1/(receipts|subscribers)/*,requires-body=1,script-path=https://raw.githubusercontent.com/89996462/Quantumult-X/main/ycdz/hsfs.js
[MITM] 
hostname = %APPEND% api.revenuecat.com