#!name=幻影相册
#!desc=幻影相册VIP
#!icon=https://raw.githubusercontent.com/deezertidal/private/main/icons/hyxc.png
#!homepage=https://yfamily.ml
#!author=89996462

[Script]
幻影相册=type=http-response,pattern=^https?:\/\/buy\.itunes\.apple\.com\/verifyReceipt$,requires-body=1,script-path=https://raw.githubusercontent.com/89996462/Quantumult-X/main/ycdz/hyxc.js

[MITM]
hostname = %APPEND% buy.itunes.apple.com