#!name=简讯
#!desc=简讯解锁会员
#!homepage=https://yfamily.ml
#!author= 89996462
#!icon=https://raw.githubusercontent.com/deezertidal/private/main/icons/jianxun.png

[MITM]
hostname = %APPEND% api.tipsoon.com

[Script]
简讯=type=http-response,pattern=^https:\/\/api\.tipsoon\.com\/api\/v1\/user\/info,requires-body=1,script-path=https://raw.githubusercontent.com/89996462/Quantumult-X/main/ycdz/JX.js

[URL Rewrite]
^https?:\/\/api\.tipsoon\.com\/api\/v1\/top\/ad _ reject-img