#!name=看理想
#!desc=看理想解锁会员
#!homepage=https://github.com/deezertidal
#!author=89996462
#!icon=https://raw.githubusercontent.com/deezertidal/private/main/icons/klx.png

[Script]
看理想=type=http-response,pattern=^https:\/\/api\.vistopia\.com\.cn\/api,requires-body=1,script-path=https://raw.githubusercontent.com/89996462/Quantumult-X/main/ycdz/kanlixiang.js

[MITM] 
hostname = %APPEND% api.vistopia.com.cn