#!name=灵敢足迹
#!desc=灵敢足迹解锁会员
#!homepage=https://yfamily.ml
#!author=89996462
#!icon=https://raw.githubusercontent.com/deezertidal/private/main/icons/lgzj.png

[Script]
灵敢足迹=type=http-response,pattern=^https:\/\/footprint-api\.quthing\.com\/vip\/state,requires-body=1,script-path=https://raw.githubusercontent.com/89996462/Quantumult-X/main/ycdz/lgzj.js
[MITM] 
hostname = %APPEND% footprint-api.quthing.com