#!name=Lifeviewer
#!desc=Lifeviewer解锁会员
#!homepage=https://yfamily.ml
#!author=89996462
#!icon=https://raw.githubusercontent.com/deezertidal/private/main/icons/lifeviewer.png

[Script]
Lifeviewer=type=http-response,pattern=^https:\/\/api\.apphud\.com\/v1\/subscriptions,requires-body=1,script-path=https://raw.githubusercontent.com/89996462/Quantumult-X/main/ycdz/Lifeviewer.js
[MITM] 
hostname = %APPEND% api.apphud.com