#!name=Lingokids
#!desc=Lingokids解锁会员
#!homepage=https://yfamily.ml
#!author= 89996462
#!icon=https://raw.githubusercontent.com/deezertidal/private/main/icons/lingokids.png
[MITM]
hostname = %APPEND% api.lingokids.com
[Script]
Lingokids=type=http-response,pattern=^https:\/\/api\.lingokids\.com\/v1\/renovate_session,requires-body=1,script-path=https://raw.githubusercontent.com/89996462/Quantumult-X/main/ycdz/Lingokids.js
