#!name=螺畤大语文
#!desc=螺畤大语文解锁会员
#!homepage=https://yfamily.ml
#!author= lutqhysky
#!icon=https://raw.githubusercontent.com/deezertidal/private/main/icons/lsdyw.png



[MITM]
hostname = %APPEND% api8.luosijiaoyu.com

[Script]
螺畤大语文=type=http-response,pattern=^https?:\/\/api8\.luosijiaoyu\.com\/api\/(HZLSJY20200817Controller\/selectFMVideoById\.html|LsjyMyContoller\/selectUserInfo\.html),requires-body=1,script-path=https://raw.githubusercontent.com/lutqhysky/quantumultx/mylove/luosidayuwen/Script/luosidayuwen.js