#!name=Motivation
#!desc=Motivation解锁会员
#!homepage=https://yfamily.ml
#!author= 89996462
#!icon=https://raw.githubusercontent.com/deezertidal/private/main/icons/motivation.png
[MITM]
hostname = %APPEND% buy.itunes.apple.com
[Script]
Motivation=type=http-response,pattern=^https:\/\/buy\.itunes\.apple\.com\/verifyReceipt,requires-body=1,script-path=https://raw.githubusercontent.com/89996462/Quantumult-X/main/ycdz/Motivation.js