#!name=猫头鹰文件
#!desc=猫头鹰文件解锁会员
#!homepage=https://yfamily.ml
#!author=89996462
#!icon=https://raw.githubusercontent.com/deezertidal/private/main/icons/mtywj.png



[Script]
猫头鹰文件=type=http-response,pattern=^https:\/\/www\.skyjos\.cn:58080\/ws\/loadaccountinfo,requires-body=1,script-path=https://raw.githubusercontent.com/89996462/Quantumult-X/main/ycdz/mtywj.js



[MITM] 
hostname = %APPEND% www.skyjos.cn
