#!name=MultiSearch
#!desc=多重搜索
#!homepage=https://github.com/deezertidal
#!author=deezertidal
#!icon=https://raw.githubusercontent.com/deezertidal/private/main/icons/multisearch.png

/*
自用 请根据需求自行修改
默认Google搜索
wk+空格+关键词(维基百科)
bd+空格+关键词(百度)
gh+空格+关键词(GitHub)
gi+空格+关键词(Google 图片)
yd+空格+关键词(有道词典)
trc+空格+关键词(Google 译至中)
tre+空格+关键词(Google 译至英)
db+空格+关键词(豆瓣)
zh+空格+关键词(知乎)
wb+空格+关键词(微博)
ddg+空格+关键词(DuckDuckGo)
bi+空格+关键词(Bing)
*/

[URL Rewrite]
^https:\/\/www\.google\.com\/search\?q=wk(\+|%20)([^&]+).+ 302 https://zh.wikipedia.org/wiki/$2
^https:\/\/www\.google\.com\/search\?q=bd(\+|%20)([^&]+).+ 302 https://www.baidu.com/s?wd=$2
^https:\/\/www\.google\.com\/search\?q=gh(\+|%20)([^&]+).+ 302 https://github.com/search?q=$2
^https:\/\/www\.google\.com\/search\?q=gi(\+|%20)([^&]+).+ 302 https://www.google.com/search?&tbm=isch&q=$2
^https:\/\/www\.google\.com\/search\?q=yd(\+|%20)([^&]+).+ 302 https://dict.youdao.com/search?q=$2
^https:\/\/www\.google\.com\/search\?q=trc(\+|%20)([^&]+).+ 302 https://translate.google.com/#view=home&op=translate&sl=auto&tl=zh-CN&text=$2
^https:\/\/www\.google\.com\/search\?q=tre(\+|%20)([^&]+).+ 302 https://translate.google.com/#view=home&op=translate&sl=auto&tl=en&text=$2
^https:\/\/www\.google\.com\/search\?q=db(\+|%20)([^&]+).+ 302 https://www.douban.com/search?q=$2
^https:\/\/www\.google\.com\/search\?q=zh(\+|%20)([^&]+).+ 302 https://www.zhihu.com/search?q=$2
^https:\/\/www\.google\.com\/search\?q=wb(\+|%20)([^&]+).+ 302 https://s.weibo.com/weibo/$2
^https:\/\/www\.google\.com\/search\?q=ddg(\+|%20)([^&]+).+ 302 https://duckduckgo.com/?ia=about&q=$2
^https:\/\/www\.google\.com\/search\?q=bi(\+|%20)([^&]+).+ 302 http://www.bing.com/search?q=$2

[MITM]
hostname = %APPEND% www.google.com
