#!name=Notability Plus
#!desc=Notability解锁
#!icon=https://raw.githubusercontent.com/deezertidal/private/main/icons/notability.png
#!homepage=https://yfamily.ml
#!author=litieyin

[MITM]
hostname = %APPEND% notability.com

[Script]
Notability=type=http-response,pattern=^https://notability.com/subscriptions,requires-body=1,script-path=https://raw.githubusercontent.com/litieyin/AD_VIP/main/Script/notability.js