#!name=Noted
#!desc=Noted解锁会员
#!homepage=https://github.com/deezertidal
#!author= 89996462
#!icon=https://raw.githubusercontent.com/deezertidal/private/main/icons/noted.png

[MITM]
hostname = %APPEND% ubscription-api.notedapp.io

[Script]
Noted=type=http-response,pattern=^https:\/\/subscription-api\.notedapp\.io\/api\/verifyReceipt,requires-body=1,script-path=https://raw.githubusercontent.com/89996462/Quantumult-X/main/ycdz/noteb.js
