#!name=PDF Viewer
#!desc=PDF Viewer解锁会员
#!homepage=https://yfamily.ml
#!author= 89996462
#!icon=https://raw.githubusercontent.com/deezertidal/private/main/icons/pdfviewer.png
[MITM]
hostname = %APPEND% api.revenuecat.com
[Script]
PDF Viewer=type=http-response,pattern=^https:\/\/api\.revenuecat\.com\/v1\/subscribers.+,requires-body=1,script-path=https://raw.githubusercontent.com/89996462/Quantumult-X/main/ycdz/PDFViewer.js
