#!name=Percento
#!desc=Percento解锁会员
#!homepage=https://yfamily.ml
#!author= 89996462
#!icon=https://raw.githubusercontent.com/deezertidal/private/main/icons/percento.png

[MITM]
hostname = %APPEND% api.revenuecat.com

[Script]
Percento=type=http-response,pattern=^https?:\/\/api\.revenuecat\.com\/v1\/(receipts|subscribers\/\$RCAnonymousID%3A\w{32})$,requires-body=1,script-path=https://raw.githubusercontent.com/89996462/Quantumult-X/main/ycdz/percento.js
