#!name=Picsart
#!desc=picsart解锁会员
#!icon=https://raw.githubusercontent.com/deezertidal/private/main/icons/picsart.png
#!homepage=https://yfamily.ml
#!author=NobyDa
[Script]
Picsart=type=http-response,pattern=https:\/\/api\.(picsart|meiease)\.c(n|om)\/users\/show\/me\.json,requires-body=1,max-size=0,script-path=https://raw.githubusercontent.com/NobyDa/Script/master/Surge/JS/PicsArt.js

[MITM]
hostname = %APPEND% api.picsart.c*, api.meiease.c*
