#!name=proKnockout
#!desc=proKnockout解锁会员
#!icon=https://raw.githubusercontent.com/deezertidal/private/main/icons/proknockout.png
#!homepage=https://yfamily.ml
#!author=lutqhysky

[MITM]
hostname= %APPEND% buy.itunes.apple.com

[Script]
proKnockout=type=http-response,pattern=https://buy.itunes.apple.com/verifyReceipt,requires-body=1,max-size=0,script-path= https://raw.githubusercontent.com/deezertidal/shadowrocket-rules/main/js/proKnockout.js
