#!name=青柠海报
#!desc=青柠海报设计解锁
#!author=89996462
#!icon=https://raw.githubusercontent.com/deezertidal/private/main/icons/qnhb.png
#!homepage=https://yfamily.ml

[Script]
青柠海报=type=http-response,pattern=^https:\/\/api\.qingning6\.com\/api\/user\/getUserInfo ,requires-body=1,script-path=https://raw.githubusercontent.com/89996462/Quantumult-X/main/ycdz/qnhb.js

[mitm]
hostname= %APPEND% api.qingning6.com