#!name=私密相册管家
#!desc=私密相册管家解锁会员
#!homepage=https://yfamily.ml
#!author=89996462
#!icon=https://raw.githubusercontent.com/deezertidal/private/main/icons/smxcgj.png

[Script]
私密相册管家=type=http-response,pattern=^https:\/\/buy\.itunes\.apple\.com\/verifyReceipt,requires-body=1,script-path=https://raw.githubusercontent.com/89996462/Quantumult-X/main/ycdz/smxcgj.js
[MITM] 
hostname = %APPEND% buy.itunes.apple.com