#!name=Sorted
#!desc=Sorted日历解锁
#!homepage=https://yfamily.ml
#!author=89996462
#!icon=https://raw.githubusercontent.com/deezertidal/private/main/icons/sorted.png
[Script]
Sorted=type=http-response,pattern=^https:\/\/api\.sortedapp\.com\/receipts\/verify,requires-body=1,script-path=https://raw.githubusercontent.com/89996462/Quantumult-X/main/ycdz/Sorted.js


[MITM]
hostname = %APPEND% api.sortedapp.com