#!name=Spotify歌词翻译
#!desc=自行修改自己的appid和密钥
[Script]
spotify歌词翻译 = type=http-response,pattern=^https:\/\/spclient\.wg\.spotify\.com\/color-lyrics\/v2\/track\/,requires-body=1,binary-body-mode=1,max-size=0,script-path=https://raw.githubusercontent.com/app2smile/rules/master/js/spotify-lyric.js,argument=appid=此处填入APPID&securityKey=此处填入密钥

/*

-----------申请百度翻译(有标准版和高级版 建议申请高级版)api--------------
2022年8月1日起，通用翻译API标准版免费调用量调整为5万字符/月，高级版免费调用量调整为100万字符/月
    注册百度翻译个人开发者: http://api.fanyi.baidu.com/register
    注册后如果需要认证可自行选择是否实人认证(高级版需要验证)
    开通(通用翻译)API服务: https://fanyi-api.baidu.com/choose
    成功后即可看到自己的appid和密钥(不要泄露给任何人): http://api.fanyi.baidu.com/manage/developer

*/

[MITM]
hostname = %APPEND% spclient.wg.spotify.com
