#!name=Styleart
#!desc=Styleart解锁会员
#!homepage=https://yfamily.ml
#!author=89996462
#!icon=https://raw.githubusercontent.com/deezertidal/private/main/icons/iscreen.png

[Script]
iScreen=type=http-response,pattern=^https:\/\/api-aidraw\.3dmoxiu\.com\/v4\/aidraw\/user\/userInfo\/getUserInfoByToken,requires-body=1,script-path=https://raw.githubusercontent.com/89996462/Quantumult-X/main/ycdz/StyleArt.js
[MITM] 
hostname = %APPEND% api-aidraw.3dmoxiu.com
