#!name=Symbolab
#!desc=Symbolab Pro
#!homepage=https://yfamily.ml
#!author=ddgksf2013
#!icon=https://raw.githubusercontent.com/deezertidal/private/main/icons/symbolab.png
[Script]
Symbolab=type=http-response,pattern=^https?:\/\/appraven\.net\/AppRaven\/(app|social|buy),requires-body=1,script-path=https://raw.githubusercontent.com/deezertidal/private/master/js-backup/Crack/appraven.js
[MITM]
hostname = %APPEND% scibug.com
