#!name=Todo清单
#!desc=Todo清单解锁会员
#!homepage=https://yfamily.ml
#!author=89996462
#!icon=https://raw.githubusercontent.com/deezertidal/private/main/icons/todo.png

[Script]
Todo清单=type=http-response,pattern=^https:\/\/www\.evestudio\.cn\/todoList\/getDetailUser,requires-body=1,script-path=https://raw.githubusercontent.com/89996462/Quantumult-X/main/ycdz/Todo.js[MITM] 
[MITM]
hostname = %APPEND% www.evestudio.cn