#!name=TOKCAM
#!desc=TOKCAM解锁永久订阅
#!homepage=https://github.com/deezertidal
#!author=yqc007
#!icon=https://raw.githubusercontent.com/deezertidal/private/main/icons/tokcam.png

[MITM]
hostname = %APPEND% buy.itunes.apple.com

[Script]
TOKCAM=type=http-response,pattern=^https?:\/\/buy\.itunes\.apple\.com\/verifyReceipt$,script-path=https://raw.githubusercontent.com/yqc007/QuantumultX/master/TokCamFProCrack.js,requires-body=1
