#!name=淘票票评分
#!desc=支付宝内淘票票显示豆瓣评分
#!homepage=https://yfamily.ml
#!author=98kevinxiao
#!icon=https://raw.githubusercontent.com/deezertidal/private/main/icons/tpp.png

[Script]
淘票票评分=type=http-response,pattern=^https:\/\/guide-acs\.m\.taobao\.com\/gw\/mtop\.film\.mtopshowapi\.getextendshowbyid,requires-body=1,script-path=https://raw.githubusercontent.com/98kevinxiao/javascript/main/taopiaopiao.js
[MITM] 
hostname = %APPEND% guide-acs.m.taobao.com