#!name=天天豆
#!desc=天天豆解锁会员
#!homepage=https://yfamily.ml
#!author=Alex0510
#!icon=https://raw.githubusercontent.com/deezertidal/private/main/icons/ttd.png

[Script]
天天豆=type=http-response,pattern=^https?:\/\/api\.revenuecat\.com\/v1\/(receipts|subscribers\/\$RCAnonymousID%3A\w{32})$,requires-body=1,script-path=https://raw.githubusercontent.com/89996462/Quantumult-X/main/ycdz/ttd.js
[MITM] 
hostname = %APPEND% api.revenuecat.com