#!name=图图记账
#!desc=图图记账解锁永久高级版
#!homepage=https://yfamily.ml
#!author=yqc007
#!icon=https://raw.githubusercontent.com/deezertidal/private/main/icons/tutu.png

[MITM]
hostname = %APPEND% api.revenuecat.com

[Script]
图图记账=type=http-response,pattern=^https?:\/\/api\.revenuecat\.com\/v1\/(receipts|subscribers\/\$RCAnonymousID%3A\w{32})$,script-path=https://raw.githubusercontent.com/yqc007/QuantumultX/master/ToToWalletFProCrack.js,requires-body=1
