#!name=VCUS
#!desc=VCUS会员解锁
#!homepage=https://yfamily.ml
#!author=89996462
#!icon=https://raw.githubusercontent.com/deezertidal/private/main/icons/vcus.png

[Script]
VCUS=type=http-response,pattern=^https:\/\/sdk\.api\.appwheel\.com\/v1\/order\/restore,requires-body=1,script-path=https://raw.githubusercontent.com/89996462/Quantumult-X/main/ycdz/VCUS.js

[MITM] 
hostname = %APPEND% sdk.api.appwheel.com