#!name=Vista看天下
#!desc=Vista看天下会员解锁
#!homepage=https://github.com/deezertidal
#!author=lutqhysky
#!icon=https://raw.githubusercontent.com/deezertidal/private/main/icons/vista.png

[Script]
Vista看天下=type=http-response,pattern=^https?:\/\/open3\.vistastory\.com\/v3\/api\/(vip\/get_vip_info_and_recommend_mags|article\/article_detail2|my\/home\/get_home_center|vip\/get_vip_price_info),requires-body=1,script-path=https://raw.githubusercontent.com/lutqhysky/quantumultx/mylove/Vister/Script/Vister.js

[MITM]
hostname = %APPEND% open3.vistastory.com
