#!name=Watchout
#!desc=Watchout小组件解锁会员
#!homepage=https://yfamily.ml
#!author=89996462
#!icon=https://raw.githubusercontent.com/deezertidal/private/main/icons/watchout.png

[Script]
Watchout=type=http-response,pattern=^https:\/\/api\.pengranapp\.com\/1\.1\/classes\/UserInfo,requires-body=1,script-path=https://raw.githubusercontent.com/89996462/Quantumult-X/main/ycdz/Watchoutc.js
[MITM] 
hostname = %APPEND% api.pengranapp.com