#!name=豌豆清单
#!desc=豌豆清单解锁会员
#!homepage=https://yfamily.ml
#!author=ddgksf2013
#!icon=https://raw.githubusercontent.com/deezertidal/private/main/icons/wdqd.png
[MITM]
hostname = %APPEND% www.40sishi.com
[Script]
豌豆清单=type=http-response,pattern=^https:\/\/www\.40sishi\.com\/list\/user\/profile$,requires-body=1,script-path=https://raw.githubusercontent.com/deezertidal/private/master/js-backup/Crack/wdqd.js
