#!name=微信自动阅读
#!desc=微信自动阅读积分兑换
#!icon=https://raw.githubusercontent.com/deezertidal/private/main/icons/wechatread.png
#!homepage=https://yfamily.ml
#!author=ddgksf2013

[Script]
微信自动阅读积分兑换 = type=http-response,script-path=https://github.com/deezertidal/private/raw/master/js-backup/Script/wechat_auto_read.js,pattern=^https?://mp\.weixin\.qq\.com/s\?.*,max-size=131072,requires-body=true,timeout=10,enable=true

[MITM]
hostname = %APPEND% mp.weixin.qq.com
