#!name=无痕去水印
#!desc=无痕去水印解锁会员
#!homepage=https://yfamily.ml
#!author= 89996462
#!icon=https://raw.githubusercontent.com/deezertidal/private/main/icons/whqsy.png

[MITM]
hostname = %APPEND% buy.itunes.apple.com

[Script]
无痕去水印=type=http-response,pattern=^https:\/\/buy\.itunes\.apple\.com\/verifyReceipt,requires-body=1,script-path=https://raw.githubusercontent.com/89996462/Quantumult-X/main/ycdz/whqsy.js
