#!name=小影
#!desc=小影解锁
#!icon=https://raw.githubusercontent.com/deezertidal/private/main/icons/xiaoying.png
#!homepage=https://yfamily.ml
#!author=NobyDa
[Script]



小影=type=http-response,pattern=^https:\/\/(xy-viva\.kakalili|api-chn.rthdo)\.com\/api\/rest\/u\/vipVerifyReceipt,requires-body=1,max-size=0,script-path=https://raw.githubusercontent.com/NobyDa/Script/master/Surge/JS/vivavideo.js

[MITM]
hostname = %APPEND% xy-viva.kakalili.com, api-chn.rthdo.com
