#!name=Xmind思维导图
#!desc=解锁Xmind思维导图订阅到2030年
#!openUrl=https://t.me/Functional_Store_Hub
#!homepage=https://yfamily.ml
#!author=@R·E https://t.me/Functional_Store_Hub
#!manual=https://t.me/Functional_Store_Hub/10
#!icon=https://raw.githubusercontent.com/deezertidal/private/main/icons/xmind.png
#!other=Xmind.Loon.plugin

[Script]
Xmind思维导图=type=http-response,pattern=https?:\/\/www\.xmind\.(cn|net|app)\/\_res\/devices,script-path=https://raw.githubusercontent.com/I-am-R-E/Functional-Store-Hub/Master/Xmind/Script/Xmind.js,requires-body=true, timeout=10, tag=Xmind思维导图

[MITM]
hostname = %APPEND% www.xmind.cn, www.xmind.net,www.xmind.app
