#!name=小组件盒子
#!desc=小组件盒子解锁会员
#!homepage=https://yfamily.ml
#!author=89996462
#!icon=https://raw.githubusercontent.com/deezertidal/private/main/icons/xzjhz.png

[Script]
小组件盒子=type=http-response,pattern=^https:\/\/widget-box-api\.codefuture\.top\/v1\/users\/me,requires-body=1,script-path=https://raw.githubusercontent.com/89996462/Quantumult-X/main/ycdz/xzjhz.js
[MITM] 
hostname = %APPEND% widget-box-api.codefuture.top