#!name=一甜相机
#!desc=一甜相机解锁会员 
#!homepage=https://yfamily.ml
#!author=yqc007
#!icon=https://raw.githubusercontent.com/deezertidal/private/main/icons/yitian.png

[MITM]
hostname = %APPEND% m2u-api.getkwai.com

[Script]
一甜相机=type=http-response,pattern=^https?:\/\/m2u-api\.getkwai\.com\/api-server\/api\/v2\/vip\/vipUserInfo,script-path=https://raw.githubusercontent.com/yqc007/QuantumultX/master/1TianCamVipCrack.js,requires-body=1