#!name=一路听天下
#!desc=一路听天下会员解锁
#!homepage=https://github.com/deezertidal
#!author=lutqhysky
#!icon=https://raw.githubusercontent.com/deezertidal/private/main/icons/ylttx.png

[Script]
一路听天下= type=http-response,pattern=^https??:\/\/h5\.t1678\.com\/app\/api\/login\/third\/boundPhone$,requires-body=1,script-path= https://raw.githubusercontent.com/lutqhysky/quantumultx/mylove/yilutingtianxia/Script/ylttx.js[MITM]
[MITM]
hostname= %APPEND% h5.t1678.com