#!name=一木记账
#!desc=一木记账解锁会员
#!homepage=https://yfamily.ml
#!author= I-am-R-E
#!icon=https://raw.githubusercontent.com/deezertidal/private/main/icons/ymjz.png
[MITM]
hostname = %APPEND% yimuapp.com
[Script]
一木记账=type=http-response,pattern=^https?:\/\/yimuapp\.com(:8082)?\/bookkeeping\/user\/getUser\/,requires-body=1,script-path=https://raw.githubusercontent.com/I-am-R-E/QuantumultX/main/JavaScript/YiMuJiZhang.js