#!name=语文趣配音
#!desc=语文趣配音解锁会员
#!homepage=https://yfamily.ml
#!author= lutqhysky
#!icon=https://raw.githubusercontent.com/deezertidal/private/main/icons/ywqpy.png



[MITM]
hostname = %APPEND% cnapi.qupeiyin.com

[Script]
语文趣配音=type=http-response,pattern=^https?:\/\/cnapi\.qupeiyin\.com\/(user\/memberData|member|top\/showTop),requires-body=1,script-path=https://raw.githubusercontent.com/lutqhysky/quantumultx/mylove/wenyuqupeiyin/Script/yuwenqupeiyin.js