#!name=test
#!desc=test
#!author=test
#!icon=
/*

[Script]
z=type=http-response,pattern=^https:\/\/changeclothes\.szsszykj\.com\/interface\/GetIosVip.php,requires-body=1,script-path=https://raw.githubusercontent.com/89996462/Quantumult-X/main/ycdz/aihlx.js
4= type=http-response,pattern=^https?:\/\/api\.revenuecat\.com\/v1\/(receipts|subscribers\/\$RCAnonymousID%3A\w{32})$,requires-body=1,script-path=https://raw.githubusercontent.com/89996462/Quantumult-X/main/ycdz/gear.js
3= type=http-response,pattern=^https?:\/\/saomiao\.34354\.com\/api\/open\/member\/level$,requires-body=1,script-path= https://raw.githubusercontent.com/lutqhysky/quantumultx/mylove/yidondsaomianyi/Script/jdsmy.js
2= type=http-response,pattern=^https:\/\/api\.revenuecat\.com\/v1\/subscribers,requires-body=1,script-path=https://raw.githubusercontent.com/89996462/Quantumult-X/main/ycdz/blocker.js
1= type=http-response,pattern=^https??:\/\/h5\.t1678\.com\/app\/api\/login\/third\/boundPhone$,requires-body=1,script-path= https://raw.githubusercontent.com/lutqhysky/quantumultx/mylove/yilutingtianxia/Script/ylttx.js

[MITM]
hostname = %APPEND% changeclothes.szsszykj.com,api.revenuecat.com,saomiao.34354.com,h5.t1678.com
*/
[Script]
http-response ^https?:\/\/api\.revenuecat\.com\/v1\/(receipts|subscribers\/\$RCAnonymousID%3A\w{32})$ requires-body=1,script-path=https://raw.githubusercontent.com/89996462/Quantumult-X/main/ycdz/fileball.js

[mitm] 

hostname = api.revenuecat.com
